#!/bin/bash

export PATH=$HOME/conda/envs/timdimm/bin:$HOME/conda/condabin:$HOME/timdimm_tng/scripts:$PATH
export CONDA_PREFIX=$HOME/conda/envs/timdimm
export CONDA_DEFAULT_ENV=timdimm

repo_dir="${TIMDIMM_REPO_DIR:-$HOME/timdimm_tng}"

cd "$repo_dir" || exit 1

kstars > "$repo_dir/kstars.log" 2>&1 &
sleep 3
start_ekos > "$repo_dir/ekos.log" 2>&1 &

if [[ "${KSTARS_WATCHDOG:-1}" == "1" ]]; then
    nohup "$repo_dir/scripts/check_kstars" >> "$repo_dir/kstars_watchdog.log" 2>&1 < /dev/null &
fi
